few more updates to dots and some utility programs

diff --git a/dots/dot-zshrc b/dots/dot-zshrc
--- a/dots/dot-zshrc
+++ b/dots/dot-zshrc
@@ -8,6 +8,8 @@ bindkey -e
 # The following lines were added by compinstall
 zstyle :compinstall filename '/Users/tsureshkumar/.zshrc'
 
+# mac systems, python sometimes fail to load crypto lib
+export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/opt/openssl/lib:$DYLD_LIBRARY_PATH
 
 fpath=(
   /usr/local/share/zsh-completions
@@ -23,6 +25,8 @@ compinit -u
 
 # zsh plugins
 plugins=(git)
+# zsh nvm plugin to manage node instances
+plugins+=(zsh-nvm)
 
 export ZSH_THEME=bureau
 
@@ -36,9 +40,59 @@ randpw(){ LC_CTYPE=C < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-16};echo;}
 # refer https://github.com/robbyrussell/oh-my-zsh
 # to install: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
 source $HOME/my/notebook/dots/dot-oh-my-zshrc
-<<<<<<< HEAD
-source $HOME/my/notebook-private/dots/dot-DO.sh
-=======
+#source $HOME/my/notebook-private/dots/dot-DO.sh
 source $HOME/my/notebook-office/dots/zshrc
 #source $HOME/projectsrc
->>>>>>> dec3adbaa7ae2a4904a540c0306b7b2e5a9db99e
+
+# >>> conda initialize >>>
+# !! Contents within this block are managed by 'conda init' !!
+__conda_setup="$('/usr/local/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
+if [ $? -eq 0 ]; then
+    eval "$__conda_setup"
+else
+    if [ -f "/usr/local/anaconda3/etc/profile.d/conda.sh" ]; then
+        . "/usr/local/anaconda3/etc/profile.d/conda.sh"
+    else
+        export PATH="/usr/local/anaconda3/bin:$PATH"
+    fi
+fi
+unset __conda_setup
+# <<< conda initialize <<<
+
+conda deactivate
+export PATH="/usr/local/opt/ruby/bin:$PATH"
+export LDFLAGS="-L/usr/local/opt/ruby/lib"
+export CPPFLAGS="-I/usr/local/opt/ruby/include"
+export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"
+export TERM=xterm-256color
+
+#useful colors to be used in scripts
+#https://stackoverflow.com/questions/16843382/colored-shell-script-output-library
+export RCol='\e[0m'    # Text Reset
+
+# Regular           Bold                Underline           High Intensity      BoldHigh Intens     Background          High Intensity Backgrounds
+export Bla='\e[0;30m'; export BBla='\e[1;30m'; export UBla='\e[4;30m'; export IBla='\e[0;90m'; export BIBla='\e[1;90m'; export On_Bla='\e[40m'; export On_IBla='\e[0;100m';
+export Red='\e[0;31m'; export BRed='\e[1;31m'; export URed='\e[4;31m'; export IRed='\e[0;91m'; export BIRed='\e[1;91m'; export On_Red='\e[41m'; export On_IRed='\e[0;101m';
+export Gre='\e[0;32m'; export BGre='\e[1;32m'; export UGre='\e[4;32m'; export IGre='\e[0;92m'; export BIGre='\e[1;92m'; export On_Gre='\e[42m'; export On_IGre='\e[0;102m';
+export Yel='\e[0;33m'; export BYel='\e[1;33m'; export UYel='\e[4;33m'; export IYel='\e[0;93m'; export BIYel='\e[1;93m'; export On_Yel='\e[43m'; export On_IYel='\e[0;103m';
+export Blu='\e[0;34m'; export BBlu='\e[1;34m'; export UBlu='\e[4;34m'; export IBlu='\e[0;94m'; export BIBlu='\e[1;94m'; export On_Blu='\e[44m'; export On_IBlu='\e[0;104m';
+export Pur='\e[0;35m'; export BPur='\e[1;35m'; export UPur='\e[4;35m'; export IPur='\e[0;95m'; export BIPur='\e[1;95m'; export On_Pur='\e[45m'; export On_IPur='\e[0;105m';
+export Cya='\e[0;36m'; export BCya='\e[1;36m'; export UCya='\e[4;36m'; export ICya='\e[0;96m'; export BICya='\e[1;96m'; export On_Cya='\e[46m'; export On_ICya='\e[0;106m';
+export Whi='\e[0;37m'; export BWhi='\e[1;37m'; export UWhi='\e[4;37m'; export IWhi='\e[0;97m'; export BIWhi='\e[1;97m'; export On_Whi='\e[47m'; export On_IWhi='\e[0;107m';
+
+case `uname` in
+    Linux)
+        alias unescape="sed 's/\x1b\[[0-9]\{1,2\}m//g'" 
+        ;;
+    Darwin)
+        alias unescape='sed -E "s/"$'\E'"\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g"'
+        ;;
+esac
+
+
+# Journaling aliases
+alias journal='vim journal_$(date -v-1d "+%Y-%m-%d").md'
+
+#sledge:binary path
+export SLEDGE_BIN=/Users/s0t00ov/.sledge/bin
+export PATH="${PATH}:${SLEDGE_BIN}"
